name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 */2 * *"

permissions:
  contents: write

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Auto green
        run: |
          git config --local user.name "${{ github.actor }}"
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit --allow-empty -m "a commit 1 天之前 keeps your girlfriend away"
          git push
